# Generated by Django 3.2.9 on 2021-12-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_cleared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cleared',
        ),
    ]
